### ISSUE TITLE
Wrong index.html in Lab2

### ISSUE THREAD

**Issue by cueo** [doodhwala/web2.0#2]
The [index.html](https://github.com/doodhwala/web2.0/blob/master/lab/lab%202/index.html) in Lab2 is mistakenly uploaded as [this](https://github.com/doodhwala/web2.0/blob/master/class/10%20Aug/part-2/index.html).

Kindly update it with the right one.

**Comment by mohit-surana** [comment]
Thank you for bringing this to our notice.

If you look at the commit message, it mentions that this folder has "incomplete" work.
This file was meant to be used as a template.

The correct file will be uploaded once work on it has finished.

**Comment by mohit-surana** [comment]
Another partial update has been pushed.
Do refer the latest version of the file.

The final version should be ready in a few hours.

https://github.com/doodhwala/web2.0/commit/b30a77c5d3f365de04d6fc5c915660fc34cb6b53#diff-1288ff70f4a8e32425b180f107cd426c

**Comment by mohit-surana** [comment]
The final version is ready

**Comment by Coldsp33d** [comment]
shut the f up niggaz
